apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: fuzail1991/ecommerce-admin-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: GRPC_HOST
              value: "0.0.0.0"
            - name: GRPC_PORT
              value: "30001"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
    - protocol: TCP
      port: 30001
      targetPort: 30001
